### ISSUE TITLE
Touch input

### ISSUE THREAD

**Issue by rugk** [rfbproto/rfbproto#17]
I've been told to request support for touch in VNC here.

So:

-----

It would be great if you supported touch input. smile

You know, I guess many more devices will support touch in the future and many already do…

----
from https://github.com/LibVNC/libvncserver/issues/265

**Comment by CendioOssman** [comment]
I'm afraid we only document things already implemented (or being implemented) rather than try to steer things by writing specifications first. So if libvncserver decides to implement something then we'll be happy to include it here.

(We also already have documentation for the GII extension, which should to basic touch events)
